API-40: Add support to create Date object from int
One user noticed that when transferring data object through RPC that is
sufficiently close to epoch start (1970-01-01 00:00:00), we won't be
able to re-construct it on the other side with exception similar to the
following:

com.streamsets.pipeline.lib.parser.DataParserException: DATA_PARSER_02 -
Parser error: 'java.lang.IllegalArgumentException: Cannot convert
Integer field '54000000' to Date'

Looking around, jackson is trying to be smart and if the transferred
number is sufficiently small it will return int rather then original
long type. This is probably somehow expected as JSON doesn't have a
proper type to distinguish int from long. I propose to simply allow our
DATE to be constructed from int as well from long to workaround this.

Change-Id: Iac7a53038587772b8a4d87fddc73cae11649a9c6
Reviewed-on: https://review.streamsets.net/3626
Tested-by: StreamSets CI <streamsets-ci-spam@streamsets.com>
Reviewed-by: Bryan Duxbury <bryan@streamsets.com>
(cherry picked from commit c896bcb80ef54463ca61312bcce0db68442af14f)
Reviewed-on: https://review.streamsets.net/3627
Reviewed-by: Jarcec Cecho <jarcec@streamsets.com>